-- =====================================================================
-- File   : 02_auth_and_users.sql
-- Purpose: Roles, application users, audit trail
-- =====================================================================

-- ---------------------------------------------------------------------
-- roles
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.roles (
    role_id      SMALLINT     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code         TEXT         NOT NULL UNIQUE
                              CHECK (code IN ('ADMIN', 'MANAGER', 'USER')),
    name         TEXT         NOT NULL,
    description  TEXT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE erp.roles IS 'Three-level access model from the scope report. ADMIN = everything, MANAGER = full read + operations, USER = own records and non-financial data only.';

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.users (
    user_id        BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username       TEXT         NOT NULL UNIQUE,
    email          TEXT         NOT NULL UNIQUE,
    full_name      TEXT         NOT NULL,
    password_hash  TEXT         NOT NULL,
    role_id        SMALLINT     NOT NULL REFERENCES erp.roles(role_id),
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT users_email_format_chk CHECK (email LIKE '%@%.%')
);

CREATE INDEX IF NOT EXISTS idx_users_role     ON erp.users(role_id);
CREATE INDEX IF NOT EXISTS idx_users_active   ON erp.users(is_active) WHERE is_active;

DROP TRIGGER IF EXISTS trg_users_updated_at ON erp.users;
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON erp.users
    FOR EACH ROW EXECUTE FUNCTION erp.set_updated_at();

COMMENT ON COLUMN erp.users.password_hash IS 'bcrypt hash. Generated by pgcrypto crypt(pw, gen_salt(''bf'')) in seed data; bcryptjs-compatible for NextAuth.';

-- ---------------------------------------------------------------------
-- Convenience view used by the auth layer and by RLS policies
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW erp.v_users AS
SELECT u.user_id,
       u.username,
       u.email,
       u.full_name,
       r.code  AS role_code,
       r.name  AS role_name,
       u.is_active,
       u.last_login_at,
       u.created_at
FROM erp.users u
JOIN erp.roles r ON r.role_id = u.role_id;

-- ---------------------------------------------------------------------
-- audit_log  (append-only)
-- Every write the application makes to a business table should land here.
-- This is what the Evidence / Audit panel replays.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.audit_log (
    audit_id       BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor_user_id  BIGINT       REFERENCES erp.users(user_id),
    actor_role     TEXT,
    action         TEXT         NOT NULL
                                CHECK (action IN ('INSERT', 'UPDATE', 'DELETE',
                                                  'LOGIN', 'LOGOUT', 'CONFIRM',
                                                  'CANCEL', 'AI_QUERY', 'EXPORT')),
    entity_schema  TEXT,
    entity_table   TEXT,
    entity_id      BIGINT,
    old_values     JSONB,
    new_values     JSONB,
    ip_address     INET,
    occurred_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_actor   ON erp.audit_log(actor_user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity  ON erp.audit_log(entity_table, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_time    ON erp.audit_log(occurred_at DESC);

DROP TRIGGER IF EXISTS trg_audit_append_only ON erp.audit_log;
CREATE TRIGGER trg_audit_append_only
    BEFORE UPDATE OR DELETE ON erp.audit_log
    FOR EACH ROW EXECUTE FUNCTION erp.forbid_update_delete();
